oadp_prow_templates:
    e2e_common_steps_template: &e2e_common_steps_template
      dependencies:
        OO_INDEX: ci-index
      env:
        OO_CHANNEL: stable
        OO_INSTALL_NAMESPACE: openshift-adp
        OO_PACKAGE: oadp-operator
        OO_TARGET_NAMESPACES: '!install'
    e2e_common_template: &e2e_common_template
      cli: latest
      credentials:
      - mount_path: /var/run/oadp-credentials
        name: oadp-credentials
        namespace: test-credentials
      from: test-oadp-operator
      resources:
        requests:
          cpu: 1000m
          memory: 512Mi
    unit_common_template: &unit_common_template
      from: src
      resources:
        requests:
          cpu: 100m
          memory: 200Mi

base_images:
  rhel-8-golang-1.20:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.20-openshift-4.14
build_root:
  image_stream_tag:
    name: builder
    namespace: ocp
    tag: rhel-8-golang-1.20-openshift-4.14
images:
- dockerfile_path: Dockerfile
  from: rhel-8-golang-1.20
  to: oadp-operator
- dockerfile_path: build/ci-Dockerfile
  from: rhel-8-golang-1.20
  to: test-oadp-operator
operator:
  bundles:
  - dockerfile_path: build/Dockerfile.bundle
  substitutions:
  - pullspec: quay.io/konveyor/oadp-operator:latest
    with: oadp-operator
releases:
  latest:
    release:
      channel: fast
      version: "4.11"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 512Mi
tests:
- as: operator-unit-test
  steps:
    test:
    - as: unit
      commands: HOME=$(pwd) make test
      <<: *unit_common_template
- as: operator-unit-test-coverage
  postsubmit: true
  steps:
    test:
    - as: unit-coverage
      commands: HOME=$(pwd) make test submit-coverage
      <<: *unit_common_template
- as: operator-unit-test-periodic
  cron: 0 4 * * *
  steps:
    test:
    - as: unit-periodic
      commands: HOME=$(pwd) make test submit-coverage
      <<: *unit_common_template
- as: operator-e2e-aws
  steps:
    cluster_profile: aws
    <<: *e2e_common_steps_template
    test:
    - as: e2e
      commands: CLUSTER_PROFILE=aws make test-e2e
      <<: *e2e_common_template
    workflow: optional-operators-ci-aws
- as: operator-e2e-azure
  steps:
    cluster_profile: azure4
    <<: *e2e_common_steps_template
    test:
    - as: e2e
      commands: CLUSTER_PROFILE=azure make test-e2e
      <<: *e2e_common_template
    workflow: optional-operators-ci-azure
- as: operator-e2e-gcp
  steps:
    cluster_profile: gcp
    <<: *e2e_common_steps_template
    test:
    - as: e2e
      commands: CLUSTER_PROFILE=gcp make test-e2e
      <<: *e2e_common_template
    workflow: optional-operators-ci-gcp
- as: operator-e2e-aws-periodic-slack
  cron: 0 4 * * *
  steps:
    cluster_profile: aws
    <<: *e2e_common_steps_template
    test:
    - as: e2e
      commands: CLUSTER_PROFILE=aws make test-e2e
      <<: *e2e_common_template
    workflow: optional-operators-ci-aws
- as: operator-e2e-gcp-periodic-slack
  cron: 0 4 * * *
  steps:
    cluster_profile: gcp
    <<: *e2e_common_steps_template
    test:
    - as: e2e
      commands: CLUSTER_PROFILE=gcp make test-e2e
      <<: *e2e_common_template
    workflow: optional-operators-ci-gcp
- as: operator-e2e-azure-periodic-slack
  cron: 0 4 * * *
  steps:
    cluster_profile: azure4
    <<: *e2e_common_steps_template
    test:
    - as: e2e
      commands: CLUSTER_PROFILE=azure make test-e2e
      <<: *e2e_common_template
    workflow: optional-operators-ci-azure
zz_generated_metadata:
  branch: master
  org: openshift
  repo: oadp-operator
  variant: "4.11"
