base_images:
  base:
    name: ubi-minimal
    namespace: ocp
    tag: "9"
  cli:
    name: "4.17"
    namespace: ocp
    tag: cli
build_root:
  image_stream_tag:
    name: builder
    namespace: konveyor
    tag: ubi9-v1.22.5
images:
- dockerfile_literal: |
    FROM src
    COPY oc /usr/bin/oc
    RUN ln -s /usr/bin/oc /usr/bin/kubectl
    RUN dnf install -y podman podman-docker && dnf clean all
  from: src
  inputs:
    cli:
      paths:
      - destination_dir: .
        source_path: /usr/bin/oc
  to: velero-oadp-e2e-deployer
- dockerfile_path: Dockerfile.ubi
  multi_arch: true
  to: velero-oadp-e2e
- dockerfile_path: Dockerfile-velero-restore-helper.ubi
  multi_arch: true
  to: velero-restore-helper-oadp-e2e
releases:
  latest:
    candidate:
      product: ocp
      stream: nightly
      version: "4.16"
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 512Mi
tests:
- always_run: false
  as: e2e-test-aws
  optional: true
  run_if_changed: (\.sh|\.go|config/.*|cmd/.*|assets/.*|internal/.*|Dockerfile.*|Makefile.*)$
  steps:
    cluster_profile: aws
    test:
    - as: deploy-oadp-for-velero
      commands: |
        make -f Makefile.prow deploy-olm
      from: velero-oadp-e2e-deployer
      resources:
        requests:
          cpu: 500m
          memory: 1Gi
    - as: run-oadp-e2e-with-velero-image
      commands: |
        make -f Makefile.prow test-e2e
      credentials:
      - mount_path: /var/run/oadp-credentials
        name: oadp-credentials
        namespace: test-credentials
      from: src
      resources:
        requests:
          cpu: 1000m
          memory: 512Mi
    workflow: ipi-aws
  timeout: 8h0m0s
zz_generated_metadata:
  branch: konveyor-dev
  org: openshift
  repo: velero
  variant: "4.16"
